from openai import OpenAI
import httpx
import sys
import os

# Get absolute path of the project root directory
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# Add project root to system path
sys.path.append(project_root)

# Load LLM configuration
model_name = ""
api_key = ""
base_url = ""

client = OpenAI(
    base_url=base_url,
    api_key=api_key,
    http_client=httpx.Client(verify=False)
)

def get_llm_response(prompt: str) -> str:
    """
    Send a prompt to the LLM and return the generated response.
    
    Args:
        prompt: Input prompt string for the model
        
    Returns:
        Response content generated by the LLM
    """
    response = client.chat.completions.create(
        model=model_name,  # "gpt-4o-mini"
        messages=[{"role": "user", "content": prompt}],
        max_tokens=4096
    )
    return response.choices[0].message.content